# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11W-YYn6l2Iz015VTrea6UJy-mIVlmL30
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("task 2 dataset.csv")


print("First 5 rows of the dataset:")
print(df.head())

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")


print("\nMissing Values:")
print(df.isnull().sum())


if 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'])


print("\nData types:")
print(df.dtypes)


if 'region' in df.columns and 'estimated_unemployment_rate' in df.columns:
    plt.figure(figsize=(12, 6))
    sns.barplot(data=df, x='region', y='estimated_unemployment_rate')
    plt.xticks(rotation=90)
    plt.title("Unemployment Rate by Region")
    plt.tight_layout()
    plt.show()


if 'date' in df.columns and 'estimated_unemployment_rate' in df.columns:
    plt.figure(figsize=(12, 6))
    sns.lineplot(data=df, x='date', y='estimated_unemployment_rate', hue='region')
    plt.title("Unemployment Rate Trend Over Time")
    plt.xlabel("Date")
    plt.ylabel("Unemployment Rate (%)")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()


plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()